# Generated by Django 5.1.7 on 2025-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=400)),
                ('img', models.ImageField(upload_to='product/')),
                ('stock', models.PositiveBigIntegerField()),
            ],
        ),
    ]
